name: static_resources_app
description: A Flutter app demonstrating static resources like images and fonts.

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CustomFont.ttf
